server:
  port: 8084

concord:
  mongo:
    enabled: true
    uri: localhost:27017
    database: readhub
    credentials:
      username: admin
      password: password
    monitoring:
      enabled: true
      log-level: DEBUG
  
  kafka:
    producer:
      enabled: true
      bootstrap-servers: localhost:9092
      serialization:
        key-serializer: org.apache.kafka.common.serialization.JsonSerializer
        value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      retry:
        attempts: 3
        backoff: 1000ms
        max-backoff: 10000ms
        backoff-multiplier: 2.0
        enable-idempotence: true
      metrics:
        enabled: true
        prefix: concord.kafka.producer
      schema-registry:
        enabled: true
        url: http://localhost:8081

logging:
  level:
    kz.readhub: DEBUG
    kz.concord: DEBUG
    org.springframework.kafka: INFO
    org.springframework.data.mongodb: DEBUG
    com.mongodb: DEBUG
  file:
    name: logs/book-management-service-local.log

management:
  endpoints:
    web:
      exposure:
        include: "*"