server:
  port: 8084

concord:
  mongo:
    enabled: true
    uri: localhost:27017
    database: readhub
    credentials:
      username: admin
      password: password
    monitoring:
      enabled: true
      log-level: DEBUG
  
  kafka:
    producer:
      enabled: true
      bootstrap-servers: localhost:9092
      
      serialization:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        add-type-headers: true
        properties:
          spring.json.add.type.headers: true
      
      retry:
        attempts: 3
        backoff: 1000ms
        max-backoff: 10000ms
        backoff-multiplier: 2.0
        enable-idempotence: true
        max-in-flight-requests-per-connection: 5
      
      metrics:
        enabled: true
        prefix: concord.kafka.producer
        recording-level: 30s
        tags:
          application: ${spring.application.name}
          environment: local
      
      tracing:
        enabled: true
        service-name: ${spring.application.name}
        sampling-probability: 1.0
      
      additional-properties:
        compression.type: snappy
        batch.size: 16384
        linger.ms: 5
        buffer.memory: 33554432

logging:
  level:
    kz.readhub: DEBUG
    kz.concord: DEBUG
    org.springframework.kafka: INFO
    org.springframework.data.mongodb: DEBUG
    com.mongodb: DEBUG
  file:
    name: logs/book-management-service-local.log

management:
  endpoints:
    web:
      exposure:
        include: "*"